### ISSUE TITLE
Cart is reset if payment fails or is cancelled

### ISSUE THREAD

**Issue by thesfboy** [razorpay/razorpay-woocommerce#131]
The cart gets reset if payment fails or if customer cancels the transaction. This means, the customer has to look for the products again and then add to the cart. This could lead to the customer just walking off from the site and not returning. When will this be corrected? Doesn't happen with PayPal or PayTM.

**Comment by harman28** [comment]
Which version of razorpay-woocommerce are you using?

**Comment by thesfboy** [comment]
2.3.0

**Comment by harman28** [comment]
Thank you for reporting this. We think this might be an issue in our latest release, 2.3.0. We're working on a fix now, and will release it soon. 

If you'd rather not wait, you also can consider using [an older release](https://github.com/razorpay/razorpay-woocommerce/releases/tag/v2.1.0).

**Comment by thesfboy** [comment]
Thanks. The older release is really crap. I kept getting literally hundreds
of mails saying Webhook failed.

**Comment by harman28** [comment]
Can you share the content of one of the webhook failure mails here? The mail should ideally contain the error message that Razorpay received when trying to send a webhook to your server.

**Comment by harman28** [comment]
Alternately, if you're willing to share your merchant ID here, I can take a look at the webhook failures myself.

**Comment by thesfboy** [comment]
B1cucsWbusBG1y

**Comment by thesfboy** [comment]
Thanks for helping out. Let me know once you've copied the id so that I can
delete it from here.

**Comment by harman28** [comment]
I have copied it. However, merchant IDs can be shared publicly, they do not grant access to any private resources or APIs.

**Comment by thesfboy** [comment]
Thanks. Good to know.

**Comment by harman28** [comment]
Checked the failures that happened on 7th September [as reported here](https://github.com/razorpay/razorpay-woocommerce/issues/126). The most frequent failure reason was an operation timeout message that we received mostly between 4.30am and 9am:
```
No response received due to network issues: cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
<img width="825" alt="Screenshot 2019-11-05 at 1 25 00 PM" src="https://user-images.githubusercontent.com/4201494/68188985-71db7900-ffd0-11e9-96ae-db3b509874fc.png">

It'll be hard to debug what exactly went wrong during this time without access to your server logs, but from the looks of things your server was simply acting up and showing high latency for this 5 hour period, causing webhooks requests to fail and subsequently be retried.

There's also a spike in successful webhook deliveries starting at 9am, which I take to mean that the failing webhooks _did_ eventually get delivered, just after a lot of attempts:
<img width="792" alt="Screenshot 2019-11-05 at 1 20 25 PM" src="https://user-images.githubusercontent.com/4201494/68189007-7f90fe80-ffd0-11e9-8dba-0adcecdba9ee.png">

Our webhooks are configured to keep retrying until there's a 24-hour period of no successes, following which the webhook is disabled. I understand that the avalanche of failure notification emails can be quite annoying for a site admin, especially one who's already facing server issues in other parts of their app, which caused the failures in the first place. There should probably be more effective throttling on emails in general. 

If you have any other suggestions about how this could've been better handled, i.e. how a failing webhook should be effectively notified to the site admin without flooding one's inbox, please let me know. I'll try and get it added to our roadmap for the next quarter.

**Comment by thesfboy** [comment]
Well. My site was definitely up and running and we logged quite a few
transactions through other gateways. No the first time this happened with
Razorpay. None of my other webhooks had this issue.

**Comment by harman28** [comment]
In that case, would you be able to check your logs and tell us why webhook requests sent to your server were regularly showing a response time of over 10 seconds? Might have been a temporary thing, since it hasn't recurred.

**Comment by thesfboy** [comment]
Sorry, can't do that. Don't have the time or resources. I have stopped
using Razorpay because of these issues. Have not faced a single issue using
PayPal or PayTM. Had escalated this issue several times over the past
several months. Do check my tickets. Would get the standard response that
our team is checking the issue and will get back to me. You are the first
person who's actively looking into this. Thanks for that. Other users would
benefit.

**Comment by harman28** [comment]
I understand, the issue is probably a little too old for you to easily fetch logs for the same.

Leaving this issue open since it has created for a different bug, i.e. cart reset. Will close when the fix is released.

**Comment by ChetanGN** [comment]
> The cart gets reset if payment fails or if customer cancels the transaction. This means, the customer has to look for the products again and then add to the cart. This could lead to the customer just walking off from the site and not returning. When will this be corrected? Doesn't happen with PayPal or PayTM.

This issue got fixed in version [2.3.1](https://github.com/razorpay/razorpay-woocommerce/releases/tag/v2.3.1) release.

**Comment by harman28** [comment]
Thanks @ChetanGN , closing this issue.

**Comment by thesfboy** [comment]
Thanks. Will check it out.

**Comment by thesfboy** [comment]
It still hasn't been resolved.

**Comment by thesfboy** [comment]
Still happening. Take a look.. If the customer cancels the payment, the cart is getting reset. 
![Screenshot 2019-11-13 at 6 55 01 PM](https://user-images.githubusercontent.com/46074603/68767867-7c88b480-0647-11ea-9615-2f64c19bf635.png)

**Comment by T7team** [comment]
> > The cart gets reset if payment fails or if customer cancels the transaction. This means, the customer has to look for the products again and then add to the cart. This could lead to the customer just walking off from the site and not returning. When will this be corrected? Doesn't happen with PayPal or PayTM.
> 
> This issue got fixed in version [2.3.1](https://github.com/razorpay/razorpay-woocommerce/releases/tag/v2.3.1) release.

The problem is still there.

**Comment by ramth05** [comment]
> > > The cart gets reset if payment fails or if customer cancels the transaction. This means, the customer has to look for the products again and then add to the cart. This could lead to the customer just walking off from the site and not returning. When will this be corrected? Doesn't happen with PayPal or PayTM.
> > 
> > 
> > This issue got fixed in version [2.3.1](https://github.com/razorpay/razorpay-woocommerce/releases/tag/v2.3.1) release.
> 
> The problem is still there.

@T7team, Yes we are working on it and must be fixed in next release.
